id: I6932BA48
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T18:23:22+00:00'
last_modified: '2022-06-08T17:07:37.787041+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9675
  title: མགོན་པོ་འབྲི་གུང་པའི་བསྟན་སྲུང་རྣམས་ཀྱི་གསོལ་བསྐང་ཡོངས་རྫོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F993:
      image_group_id: I1KG9694
      title: ''
      total_pages: 766
      order: 1
      base_file: F993.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
