id: P010732
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:21:59.189249
source_metadata:
  id: bdr:W1KG9675
  title: མགོན་པོ་འབྲི་གུང་པའི་བསྟན་སྲུང་རྣམས་ཀྱི་གསོལ་བསྐང་ཡོངས་རྫོགས།
  author: ''
  volumes:
    be77a186ee604471a6aa8f783081050c:
      image_group_id: I1KG9694
      title: ''
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
