id: P010732
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9675
  title: མགོན་པོ་འབྲི་གུང་པའི་བསྟན་སྲུང་རྣམས་ཀྱི་གསོལ་བསྐང་ཡོངས་རྫོགས།
  author: ''
  volumes:
    be77a186ee604471a6aa8f783081050c:
      image_group_id: I1KG9694
      title: ''
      volume_number: 1
      total_pages: 766
      base_file: v001.txt
